### ISSUE TITLE
Swiping too far to either side results in no organisations showing up

### ISSUE THREAD

**Issue by gamer191** [veganhacktivists/animalrightsmap#8] opened 2022-10-26 07:21 UTC
Swiping too far to either side results in no organisations showing up. This is problematic, because if someone is extremely zoomed in (such as if they're using the https://veganactivism.org/ embed), it may appear that their country doesn't have any organisations.

**Comment by stephan281094** [comment] 2024-03-04 16:56
Hi there! Thank you so much for reporting, and our apologies for not picking this up earlier.

We've looked at the issue and we are indeed able to reproduce it ourselves. It looks like it's an issue with the map creator that we're using from the [uMap project](https://umap-project.org). Until this issue gets fixed over there, this isn't something we can fix on our end, unfortunately. Closing this for now.

**Closed as completed by stephan281094** 2024-03-04 16:56 UTC
